micronaut:
  application:
    name: expen-share
  server:
    port: 8080
  validation:
    enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    enabled: true
    csrf:
      enabled: false
    intercept-url-map:
      - pattern: /**
        access:
          - isAnonymous()
  metrics:
    enabled: true


datasources:
  default:
    url: jdbc:h2:mem:expenshare;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: ""
    schema-generate: NONE
    dialect: H2

flyway:
  datasources:
    default:
      enabled: true

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: false
        format_sql: true



kafka:
  bootstrap:
    servers: localhost:9092
  producers:
    default:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  consumers:
    default:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: expen-share-group

endpoints:
  h2:
    enabled: true
    sensitive: false
