micronaut:
  application:
    name: expen-share
  server:
    port: 8080
  validation:
    enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    enabled: true
    csrf:
      enabled: false
    intercept-url-map:
      - pattern: /**
        access:
          - isAnonymous()
  metrics:
    enabled: true

datasources:
  default:
    url: jdbc:h2:mem:expen-share;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ""
    dialect: H2

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: false
        format_sql: true

flyway:
  datasources:
    default:
      enabled: true


kafka:
  bootstrap:
    servers: localhost:9092
  producers:
    default:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  consumers:
    default:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: expen-share-group
