micronaut:
  application:
    name: expen-share
  server:
    port: 8080
  validation:
    enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    enabled: true
    csrf:
      enabled: false
    intercept-url-map:
      - pattern: /h2-console/**
        access:
          - isAnonymous()
      - pattern: /**
        access:
          - isAuthenticated()
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
    authentication: bearer
  metrics:
    enabled: true

datasources:
  default:
    url: jdbc:h2:mem:expen-share;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ""
    dialect: H2

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: false
        format_sql: true

flyway:
  datasources:
    default:
      enabled: true
