CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    mobile_number VARCHAR(20),
    addr_line1 VARCHAR(150),
    addr_line2 VARCHAR(150),
    addr_city VARCHAR(80),
    addr_state VARCHAR(80),
    addr_postal VARCHAR(20),
    addr_country VARCHAR(2),
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE group_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,    group_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    added_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_group_members_group
        FOREIGN KEY (group_id) REFERENCES groups(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_group_members_user
        FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT unique_group_user UNIQUE (group_id, user_id)
);

CREATE TABLE expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,    group_id BIGINT NOT NULL,
    paid_by BIGINT NOT NULL,
    amount DECIMAL(18,2) NOT NULL,
    description VARCHAR(255) NOT NULL,
    split_type VARCHAR(20) NOT NULL CHECK (split_type IN ('EQUAL','EXACT','PERCENT')),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_expense_group FOREIGN KEY (group_id) REFERENCES groups(id),
    CONSTRAINT fk_expense_paid_by FOREIGN KEY (paid_by) REFERENCES users(id)
);

CREATE TABLE expense_shares (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,    expense_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    share_amount DECIMAL(18,2) NOT NULL,
    CONSTRAINT fk_expense_share_expense
        FOREIGN KEY (expense_id) REFERENCES expenses(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_expense_share_user
        FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE settlements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    from_user_id BIGINT NOT NULL,
    to_user_id BIGINT NOT NULL,
    amount DECIMAL(18,2) NOT NULL,
    method VARCHAR(20) DEFAULT 'OTHER' CHECK (method IN ('CASH','BANK_TRANSFER','OTHER')),
    note VARCHAR(255),
    reference VARCHAR(64),
    status VARCHAR(20) DEFAULT 'CONFIRMED' CHECK (status IN ('PENDING','CONFIRMED','CANCELED')),
    created_at TIMESTAMP NOT NULL,
    confirmed_at TIMESTAMP NULL,
    CONSTRAINT fk_settlement_group FOREIGN KEY (group_id) REFERENCES groups(id),
    CONSTRAINT fk_settlement_from_user FOREIGN KEY (from_user_id) REFERENCES users(id),
    CONSTRAINT fk_settlement_to_user FOREIGN KEY (to_user_id) REFERENCES users(id)
);